apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-deploy
  labels:
    app: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017/dev"
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
    
