apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
  labels:
    app: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: instavote/vote:indent
          ports:
            - containerPort: 80
    
