apiVersion: v1
kind: Service
metadata:
  name: knote-service
spec:
  type: NodePort
  selector:
    app: knote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30100
      name: knote-access-port
