apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql-svc-port
