apiVersion: v1
kind: Service
metadata:
  name: phpsvc
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: phpmyadmin-http-port
