apiVersion: v1
kind: Service
metadata:
  name: votesvc
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-svc-port
    - protocol: TCP
      port: 31001
      targetPort: 80
      name: optionnal-port
